Feat/home page
MaloLM/pr74-scrum-app pull request #25
Opened 2022-06-10 13:58 UTC by wilfridbeaunes

Hello guys, I worked a bit on the design of the homeForm, correct also the design of the rest and I added the link between forms mean when I close the link it brink me bacck to homeForm which was hiden(homeForm need to be close  at the end to free memory)

2022-06-10 14:11 UTC, ssan93 approved these changes

2022-06-10 14:43 UTC, MaloLM requested changes
affiner les commentaires évident (great)

2022-06-10 17:52 UTC, W3roxe approved these changes

2022-06-12 10:02 UTC, MaloLM approved these changes
bravo ! https://www.youtube.com/watch?v=dQw4w9WgXcQ

2022-06-12 11:05 UTC, merged