First version of fixtures
MaloLM/pr74-scrum-app pull request #44
Opened 2022-06-25 10:27 UTC by W3roxe

- First version of fixtures in the directory fixtures
- New method "ExecuteFixtureQuery" in the Database class

2022-06-25 10:59 UTC, wilfridbeaunes requested changes
Tu as fait du bon boulot, cependant,
-> lorsque tu fais des insertions il faut vérifier si les valeurs existe pas déja en base (l'id). d'après ce que tu as fait a chaque fois qu'on demarre le propograme ça insert automatique les vealeurs. Au second démarrage de l'appli tu auras un problème pour les Primary key.
-> il ne faut pas push le packages.config

2022-06-26 08:40 UTC, wawkadura requested changes

2022-06-26 08:40 UTC, wawkadura commented on Fixtures/Fixtures.cs
> +            string[] states = { "To do", "In progress", "Done" };
les etats : TODO, REVIEW, PROGRESS, DONE

2022-06-26 08:40 UTC, wawkadura commented on Fixtures/Fixtures.cs
> +            string[] roles = { "Product owner", "Scrum master", "Developer" };
les roles : 
SM, PO, DEV

2022-06-26 19:52 UTC, wilfridbeaunes commented on Fixtures/Fixtures.cs
> +            String queryModel = "INSERT INTO project (name, description, archived, pinned) VALUE('{0}', '{1}', {2}, {3})";
Pas de pinned dans la table projet/db mis a jour

2022-06-26 19:54 UTC, wilfridbeaunes commented on Fixtures/Fixtures.cs
> +
Add some pinned project, max 5
This table have to content pinned column

2022-06-26 20:03 UTC, wilfridbeaunes requested changes
Faut décidé de comment run ton fix, fait comme tu as fait polu le code.
Prends en compte mes modif table member qui contient une column pinned et pas project ajoute des pinned=1 et max 5 pour un membre 
Je pense qu’on va plus tôt  partir sur un export de tes données une fois qu’elle sont bien insérées  et après run de notre côté

2022-06-28 15:08 UTC, closed without merging